server:
  port: 8085
spring:
  application:
    name: MEDICAL-HISTORY-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://hospital-db-do-user-14558489-0.b.db.ondigitalocean.com:25060/medical_history_db
    username: doadmin
    password: AVNS_ZsEHpELLbPwTvabmXJN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  get-user-email : http://USER-SERVICE/user/send-email
  get-doctor: http://USER-SERVICE/user/send-doctor


eureka:
  client:
    service-url:
      default-url: ${EUREKA_URI:http://134.209.20.129:8761/eureka/}
    instance:
      preferIpAddress: true

jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F4528487782141254367566B5970337336
