server:
  port: 8085
spring:
  application:
    name: MEDICAL-HISTORY-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/medical_history_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  get-user-email : http://USER-SERVICE/user/send-email
  get-user-id : http://USER-SERVICE/user/send-id
  get-hospital-id : http://USER-SERVICE/user/send-hospital-id
  get-hospital-name : http://HOSPITAL-SERVICE/hospital/send-name
  get-doctor: http://USER-SERVICE/user/send-doctor


eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:https://127.0.0.1:8761/eureka/}
    instance:
      preferIpAddress: true

jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848567890iuyiu67567886578uyutuio7865467897654678965467uior678545
